# Generated by Django 4.0.5 on 2022-06-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pr', models.CharField(max_length=50, verbose_name='Статус продукта: ')),
            ],
            options={
                'verbose_name': ' Статус Продукта: ',
                'verbose_name_plural': 'Статус Продуктов: ',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=100, verbose_name='1')),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фотография продукта: ')),
                ('type_pr', models.CharField(max_length=100, verbose_name='Тип продукта: ')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер продукта: ')),
                ('package', models.PositiveSmallIntegerField(verbose_name='Количество упаковок: ')),
                ('pair', models.PositiveSmallIntegerField(verbose_name='Количество пар: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_pr', models.CharField(max_length=50, verbose_name='Уточним что это поля должно быть ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoesFactory.statusproduct')),
            ],
            options={
                'verbose_name': 'Продукт: ',
                'verbose_name_plural': 'Продукты: ',
            },
        ),
    ]
