# Generated by Django 4.0.5 on 2022-06-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartiesRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=150, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион:',
                'verbose_name_plural': 'Регионы:',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия:')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя:')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактный номер сотрудника:')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации:')),
            ],
            options={
                'verbose_name': 'Сотрудник:',
                'verbose_name_plural': 'Сотрудники:',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pr', models.CharField(max_length=100, verbose_name='Тип продукта: ')),
                ('date_published', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель продукта:',
                'verbose_name_plural': 'Модели продуктов:',
            },
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'verbose_name': 'Продукт:', 'verbose_name_plural': 'Продукты:'},
        ),
        migrations.AlterModelOptions(
            name='statusproduct',
            options={'verbose_name': ' Статус Продукта:', 'verbose_name_plural': 'Статус Продуктов:'},
        ),
        migrations.AlterField(
            model_name='productsale',
            name='package',
            field=models.PositiveSmallIntegerField(verbose_name='Количество упаковок:'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='pair',
            field=models.PositiveSmallIntegerField(verbose_name='Количество пар:'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Размер продукта:'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sum_pr',
            field=models.CharField(max_length=50, verbose_name='Уточним что это поля должно быть:'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='type_pr',
            field=models.CharField(max_length=100, verbose_name='Тип продукта:'),
        ),
        migrations.AlterField(
            model_name='statusproduct',
            name='status_pr',
            field=models.CharField(max_length=50, verbose_name='Статус продукта:'),
        ),
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия:')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя:')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактный номер контрагента:')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoesFactory.counterpartiesregion')),
            ],
            options={
                'verbose_name': 'Контрагент:',
                'verbose_name_plural': 'Контрагенты:',
            },
        ),
    ]
