# Generated by Django 4.0.5 on 2022-06-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0002_counterpartiesregion_employee_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparties',
            options={'verbose_name': 'Контрагент:', 'verbose_name_plural': 'Контрагентов:'},
        ),
        migrations.AlterModelOptions(
            name='counterpartiesregion',
            options={'ordering': ['id'], 'verbose_name': 'Регион:', 'verbose_name_plural': 'Регионов'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудник:', 'verbose_name_plural': 'Сотрудников:'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id'], 'verbose_name': 'Модель продукта:', 'verbose_name_plural': 'Модели продуктов:'},
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'verbose_name': 'Продукт:', 'verbose_name_plural': 'Продуктов:'},
        ),
        migrations.AlterModelOptions(
            name='statusproduct',
            options={'verbose_name': ' Статус Продукта:', 'verbose_name_plural': 'Статуса Продуктов:'},
        ),
        migrations.AlterField(
            model_name='productsale',
            name='articul',
            field=models.CharField(max_length=100, verbose_name='articul'),
        ),
    ]
