# Generated by Django 4.0.5 on 2022-07-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0003_alter_counterparties_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='Остаток средств:')),
                ('date', models.DateField(verbose_name='Дата:')),
            ],
            options={
                'verbose_name': 'Остаток:',
                'verbose_name_plural': 'Остатки:',
            },
        ),
        migrations.CreateModel(
            name='DebtOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_on', models.IntegerField(verbose_name='Задолжность:')),
                ('date', models.DateField(verbose_name='Дата:')),
            ],
            options={
                'verbose_name': 'Задолжность:',
                'verbose_name_plural': 'Задолжности:',
            },
        ),
        migrations.CreateModel(
            name='ZPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность:')),
                ('working_days', models.IntegerField(default=26, verbose_name='Раб.Дней:')),
                ('actually_worked_out', models.IntegerField(default=0, verbose_name='Факт.отработано:')),
                ('salary_for', models.IntegerField(default=0, verbose_name='Оклад для СФ:')),
                ('actualy_salary', models.IntegerField(default=0, verbose_name='Факт.оклад:')),
                ('social_fund', models.IntegerField(default=1050, verbose_name='Соц.Фонд:')),
                ('em_Soc_fund', models.IntegerField(default=1035, verbose_name='Работодатель Соц.фонд 17,25%:')),
                ('salary_on_accruals', models.IntegerField(default=0, verbose_name='Оклад по начислениям:')),
                ('piecework_machine', models.IntegerField(default=0, verbose_name='сдельная станок ПУ:')),
                ('piece_EVA', models.IntegerField(default=0, verbose_name='Сдельная ЭВА:')),
                ('accumulated', models.IntegerField(default=0, verbose_name='Начислено:')),
                ('premium', models.IntegerField(default=0, verbose_name='Премия:')),
                ('prepaid_expense', models.IntegerField(default=0, verbose_name='Аванс:')),
                ('Sale_of_goods', models.IntegerField(default=0, verbose_name='Продажа товаров:')),
                ('pay', models.IntegerField(verbose_name='Выплата:')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoesFactory.balance')),
                ('debt_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoesFactory.debton')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoesFactory.employee')),
            ],
            options={
                'verbose_name': 'Обшая Зарплата:',
                'verbose_name_plural': 'Общие Зарплаты:',
            },
        ),
    ]
