# Generated by Django 4.0.5 on 2022-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0005_alter_zpeople_balance_alter_zpeople_debt_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpeople',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default=123, max_length=100, verbose_name='Должность:'),
            preserve_default=False,
        ),
    ]
