# Generated by Django 4.0.5 on 2022-07-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0006_remove_zpeople_job_title_employee_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpeople',
            name='employee',
        ),
        migrations.AddField(
            model_name='zpeople',
            name='employee',
            field=models.ManyToManyField(to='ShoesFactory.employee', verbose_name='Сотрудник:'),
        ),
    ]
