# Generated by Django 4.0.5 on 2022-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesFactory', '0007_remove_zpeople_employee_zpeople_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default=123, max_length=150, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
